### ISSUE TITLE
SequelizeConnectionError when running `node ./migrate.js up`

### ISSUE THREAD

**Issue by remjx** [abelnation/sequelize-migration-hello#3]
I am able to connect using `sequelize.authenticate()` but when i run `node ./migrate.js up` I get the following error: 

> Unhandled rejection SequelizeConnectionError: password authentication failed for user "sequelize_demo_admin"
    at C:\Users\expo\Documents\workspace\sequelize-migration-hello\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:133:20
    at Client.<anonymous> (C:\Users\expo\Documents\workspace\sequelize-migration-hello\node_modules\pg\lib\client.js:203:5)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (C:\Users\expo\Documents\workspace\sequelize-migration-hello\node_modules\pg\lib\connection.js:133:12)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)

Any ideas what could be happening here?

**Comment by remjx** [comment]
Oops, I realized there is authentication in 2 different files: `index.js` and `migrate.js`. Problem solved!
